# Generated by Django 4.1.5 on 2023-01-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_link", models.URLField()),
                (
                    "shortened_link",
                    models.CharField(max_length=50, verbose_name="Короткий URL"),
                ),
            ],
            options={
                "verbose_name": "Ссылка",
                "verbose_name_plural": "Ссылки",
            },
        ),
    ]
