# Generated by Django 4.1.5 on 2023-01-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("link_reducer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="redirect_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
